SAMPLES = [
    # Positive
    ("Sobrang ganda ng product! Bibilhin ko ulit for sure.",         "Positive"),
    ("Worth it talaga, hindi ako nagsisi na binili ko.",              "Positive"),
    ("Ang bilis ng delivery, dumating in 2 days pa lang!",           "Positive"),
    ("Grabe ang quality, parang mas mahal pa sa presyo.",            "Positive"),
    ("Happy na happy ako sa purchase ko, highly recommended!",       "Positive"),
    ("Legit ang seller, totoong item at maayos na packaging.",       "Positive"),
    ("Ang saya, exactly as described sa photos. 5 stars!",          "Positive"),
    ("Nabigyan pa ako ng freebie, ang bait ng seller!",              "Positive"),
    ("Excellent product, maganda pa ang customer service nila.",      "Positive"),
    ("First time ko mag-order dito, hindi ako nabigo. Babalik ako!", "Positive"),
    # Negative
    ("Hindi ako satisfied, ibang item ang dumating sa akin.",        "Negative"),
    ("Grabe, peke pala yung binili ko. Scammer!",                    "Negative"),
    ("Ang tagal ng delivery, 3 weeks na wala pa rin.",               "Negative"),
    ("Sira na pagdating, parang binato nalang sa truck.",            "Negative"),
    ("Hindi tumutugma sa description, malaki ang pagkakaiba.",       "Negative"),
    ("Ayaw pang mag-refund ng seller, grabe ang kapal ng mukha.",    "Negative"),
    ("Kalidad ng basura, nabuwag agad after one week.",              "Negative"),
    ("Scam! Walang dumating na item kahit bayad na ako.",            "Negative"),
    ("Ang mahal pa naman tapos ganito ang quality? Sayang pera.",    "Negative"),
    ("Never again sa seller na ito. Lesson learned.",                "Negative"),
    # Neutral
    ("Natanggap ko na. Okay naman, walang issue so far.",            "Neutral"),
    ("Standard lang ang quality, wala masyadong reklamo.",           "Neutral"),
    ("Arrived on time. Hindi exceptional pero okay.",                "Neutral"),
    ("Magagamit naman, kahit hindi exactly what I expected.",        "Neutral"),
    ("Normal lang, kasing-ganda ng ibang products sa range na ito.", "Neutral"),
    ("Okay naman ang seller, basta naireply ang inquiry ko.",        "Neutral"),
    ("Delivery was average, a few days lang naman ang delay.",       "Neutral"),
    ("Product is as described, nothing more nothing less.",          "Neutral"),
    ("Hindi bad, hindi rin exceptional. Pwede na.",                  "Neutral"),
    ("Di maganda, di pangit. Nasa gitna lang.",                      "Neutral"),
]